### ISSUE TITLE
US#09 - Visualizar mostruário

### ISSUE THREAD

**Issue by jbisinotti** [edsondearaujo/FurnitApp_Requisitos#10]
**Eu como** cliente, **desejo** visualizar o mostruário **para** ver os produtos e promoções disponíveis na loja.

- [x] Visualizar página com todos os produtos do mostruário.

Tasks:
- [x] Buscar todos os produtos no banco de dados e retornar em forma de lista de modelos (Models)
- [x] Listar todos os produtos em uma página.

**Comment by wdvictor** [comment]
@jbisinotti, essa issue acredito que já foi realizada em outras issues. Verifica o app se ele atende a essas condições, se sim, dê ela como fechada
